const colors = {
  light: {
    text: "#0F0F0F",
    tint: "#2563EB",
    background: "#FFFFFF",
    foreground: "#0F0F0F",
    card: "#F5F5F5",
    cardForeground: "#0F0F0F",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F5F5",
    secondaryForeground: "#0F0F0F",
    muted: "#F5F5F5",
    mutedForeground: "#606060",
    accent: "#E8F0FE",
    accentForeground: "#2563EB",
    destructive: "#FF0000",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#E5E5E5",
    chipActive: "#0F0F0F",
    chipActiveText: "#FFFFFF",
    chipInactive: "#F2F2F2",
    chipInactiveText: "#0F0F0F",
  },
  dark: {
    text: "#F1F5F9",
    tint: "#60A5FA",
    background: "#0F0F0F",
    foreground: "#F1F5F9",
    card: "#1A1A1A",
    cardForeground: "#F1F5F9",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#272727",
    secondaryForeground: "#F1F5F9",
    muted: "#272727",
    mutedForeground: "#AAAAAA",
    accent: "#1E3A5F",
    accentForeground: "#93C5FD",
    destructive: "#FF0000",
    destructiveForeground: "#FFFFFF",
    border: "#272727",
    input: "#272727",
    chipActive: "#FFFFFF",
    chipActiveText: "#0F0F0F",
    chipInactive: "#272727",
    chipInactiveText: "#FFFFFF",
  },
  radius: 4,
};

export default colors;
