# Generated by Django 5.2.14 on 2026-05-16 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_video_report'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='videos.video')),
            ],
            options={
                'db_table': 'saved_videos',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user'], name='saved_video_user_id_12411e_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='videos.video')),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user'], name='watch_histo_user_id_49f38f_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
