# Generated by Django 5.2.14 on 2026-05-16 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('quran', 'Quran & Tafsir'), ('fiqh', 'Fiqh & Islamic Law'), ('seerah', 'Seerah & History'), ('aqeedah', 'Aqeedah & Theology'), ('hadith', 'Hadith & Sciences'), ('spirituality', 'Spirituality & Tazkiyah'), ('family', 'Family & Lifestyle'), ('finance', 'Islamic Finance'), ('dawah', 'Dawah & Education'), ('other', 'Other')], default='other', max_length=20)),
                ('video_type', models.CharField(choices=[('long', 'Long Video'), ('short', 'Short')], default='long', max_length=10)),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_videos', to=settings.AUTH_USER_MODEL)),
                ('scholar', models.ForeignKey(limit_choices_to={'is_scholar': True}, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='videos_status_0ab253_idx'), models.Index(fields=['scholar', 'status'], name='videos_scholar_c40235_idx'), models.Index(fields=['video_type', 'status'], name='videos_video_t_c3b496_idx')],
            },
        ),
    ]
