# Generated by Django 5.2.14 on 2026-05-16 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='video',
            new_name='video_category_idx',
            old_name='videos_status_0ab253_idx',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='video_scholar_idx',
            old_name='videos_scholar_c40235_idx',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='video_type_idx',
            old_name='videos_video_t_c3b496_idx',
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'visibility', 'created_at'], name='video_feed_idx'),
        ),
    ]
